const STORE_KEY = 'study_plan_analyzer_web_v1';
const SUBJECTS = ['数学','语文','英语','物理','化学','生物','政治','历史','地理','其他'];
const TASK_TYPES = ['作业','刷题','复习','预习','背诵','错题整理','阅读','其他'];
const PERIODS = ['06:00–09:00','09:00–12:00','12:00–15:00','15:00–18:00','18:00–21:00','21:00–24:00'];
let db = loadDb();
let currentUser = null;
let activePage = 'dashboard';
let analysisMode = 'subject';
let toastTimer;

function loadDb(){
  try { return JSON.parse(localStorage.getItem(STORE_KEY)) || {users:[],tasks:[],executions:[]}; }
  catch { return {users:[],tasks:[],executions:[]}; }
}
function saveDb(){ localStorage.setItem(STORE_KEY, JSON.stringify(db)); }
function id(){ return crypto.randomUUID ? crypto.randomUUID() : `${Date.now()}_${Math.random().toString(16).slice(2)}`; }
function today(){ return new Date().toISOString().slice(0,10); }
function escapeHtml(value){ return String(value ?? '').replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c])); }
function fmt(value){ return Number(value || 0).toLocaleString('zh-CN'); }
function pct(value){ return `${Number(value || 0).toFixed(1)}%`; }
function avg(arr){ return arr.length ? arr.reduce((a,b)=>a+b,0)/arr.length : 0; }
function showToast(message){ const el = document.querySelector('#toast'); el.textContent = message; el.classList.add('show'); clearTimeout(toastTimer); toastTimer = setTimeout(()=>el.classList.remove('show'), 2600); }
function records(){
  const tasks = db.tasks.filter(t=>t.userId===currentUser.id);
  return tasks.map(t=>({...t, execution: db.executions.find(e=>e.taskId===t.id && e.userId===currentUser.id)}));
}
function deviation(task, execution){
  if(!execution || execution.actualDuration === null || execution.actualDuration === undefined) return {minutes:0, rate:0};
  const minutes = Number(execution.actualDuration) - Number(task.plannedDuration);
  return {minutes, rate: task.plannedDuration ? minutes / task.plannedDuration * 100 : 0};
}
function statusClass(status){ return status==='已完成'?'done':status==='进行中'?'progress':status==='延期'?'delay':'pending'; }
function statusPill(status){ return `<span class="status ${statusClass(status)}">${escapeHtml(status)}</span>`; }
function setPage(page){
  activePage = page;
  document.querySelectorAll('.nav-item').forEach(el=>el.classList.toggle('active',el.dataset.page===page));
  document.querySelectorAll('.page').forEach(el=>el.classList.toggle('active',el.id===`page-${page}`));
  const labels={dashboard:'首页',plans:'学习计划',execution:'执行记录',analysis:'数据分析',recommendations:'学习建议',profile:'我的'};
  document.querySelector('#pageHeading').textContent=labels[page];
  renderPage(page);
}
function renderPage(page){
  if(page==='dashboard') renderDashboard();
  if(page==='plans') renderPlans();
  if(page==='execution') renderExecution();
  if(page==='analysis') renderAnalysis();
  if(page==='recommendations') renderRecommendations();
  if(page==='profile') renderProfile();
}
function renderDashboard(){
  const rows=records().filter(r=>r.taskDate===today());
  const done=rows.filter(r=>r.execution?.completed).length;
  const valid=rows.filter(r=>r.execution);
  const avgRate=avg(valid.map(r=>deviation(r,r.execution).rate));
  const suggestions=getRecommendations();
  document.querySelector('#page-dashboard').innerHTML=`
    <div class="page-intro"><div><h3>今天的学习计划</h3><p>${today()} · 先安排，再记录，最后复盘。</p></div><button class="primary" data-open-task>＋ 新建任务</button></div>
    <div class="stats-grid"><div class="stat-card"><span class="stat-label">今日计划</span><strong class="stat-value">${rows.length}</strong><span class="stat-foot">个学习任务</span></div><div class="stat-card"><span class="stat-label">今日完成</span><strong class="stat-value">${done}</strong><span class="stat-foot">已记录完成</span></div><div class="stat-card"><span class="stat-label">今日完成率</span><strong class="stat-value">${pct(rows.length?done/rows.length*100:0)}</strong><span class="stat-foot">按任务数量计算</span></div><div class="stat-card"><span class="stat-label">今日平均偏差</span><strong class="stat-value">${avgRate>=0?'+':''}${avgRate.toFixed(1)}%</strong><span class="stat-foot">仅统计有执行记录的任务</span></div></div>
    <div class="dashboard-grid"><div class="panel"><div class="panel-head"><h4>今日任务</h4><span>${rows.length?`共 ${rows.length} 项`:'还没有今天的计划'}</span></div>${rows.length?taskTable(rows):emptyState('还没有今天的学习任务','创建第一个计划，让今天变得更清晰。')}</div><div class="panel"><div class="panel-head"><h4>今日建议</h4><span>来自你的历史记录</span></div><div class="advice-list">${suggestions.slice(0,3).map(s=>`<div class="advice-item">${escapeHtml(s)}</div>`).join('')}</div></div></div><div class="panel dashboard-chart">${lineVisual('近 7 天计划与实际学习时间',trend(7),[['planned','计划'],['actual','实际']])}</div>`;
  bindCommon();
}
function emptyState(title,copy){return `<div class="empty"><strong>${title}</strong><span>${copy}</span></div>`;}
function taskTable(rows, actions=true){return `<div class="table-wrap"><table class="data-table"><thead><tr><th>日期</th><th>科目 / 任务</th><th>计划开始</th><th>计划时长</th><th>状态</th>${actions?'<th></th>':''}</tr></thead><tbody>${rows.map(r=>`<tr><td>${escapeHtml(r.taskDate)}</td><td><strong>${escapeHtml(r.subject)}</strong><br><span class="muted">${escapeHtml(r.taskName)}</span></td><td>${escapeHtml(r.plannedStartTime)}</td><td>${fmt(r.plannedDuration)} 分钟</td><td>${statusPill(r.status)}</td>${actions?`<td><button class="action-link" data-edit-task="${r.id}">编辑</button><button class="action-link danger" data-delete-task="${r.id}">删除</button></td>`:''}</tr>`).join('')}</tbody></table></div>`;}
function renderPlans(){
  const search=document.querySelector('#planSearch')?.value?.trim().toLowerCase()||'';
  const date=document.querySelector('#planDate')?.value||'';
  const subject=document.querySelector('#planSubject')?.value||'';
  const status=document.querySelector('#planStatus')?.value||'';
  let rows=records().filter(r=>(!search||`${r.taskName}${r.subject}`.toLowerCase().includes(search))&&(!date||r.taskDate===date)&&(!subject||r.subject===subject)&&(!status||r.status===status));
  document.querySelector('#page-plans').innerHTML=`<div class="page-intro"><div><h3>学习计划</h3><p>把想做的事安排进具体的日期和时间。</p></div><button class="primary" data-open-task>＋ 新建任务</button></div><div class="filter-bar"><input id="planSearch" class="search" placeholder="搜索任务或科目" value="${escapeHtml(search)}"><input id="planDate" type="date" value="${date}"><select id="planSubject"><option value="">全部科目</option>${SUBJECTS.map(s=>`<option ${s===subject?'selected':''}>${s}</option>`).join('')}</select><select id="planStatus"><option value="">全部状态</option>${['待完成','进行中','已完成','延期'].map(s=>`<option ${s===status?'selected':''}>${s}</option>`).join('')}</select><button class="ghost" id="applyPlanFilter">筛选</button></div><div class="panel">${rows.length?taskTable(rows):emptyState('还没有符合条件的任务','可以调整筛选条件，或创建一个新任务。')}</div>`;
  document.querySelector('#applyPlanFilter').onclick=renderPlans; document.querySelectorAll('#page-plans input,#page-plans select').forEach(el=>el.addEventListener('keydown',e=>{if(e.key==='Enter')renderPlans();})); bindCommon();
}
function renderExecution(){
  const rows=records();
  document.querySelector('#page-execution').innerHTML=`<div class="page-intro"><div><h3>执行记录</h3><p>完成任务后补充真实用时，偏差分析才会有依据。</p></div><button class="primary" data-open-execution>＋ 记录执行</button></div><div class="panel">${rows.length?`<div class="table-wrap"><table class="data-table"><thead><tr><th>日期</th><th>任务</th><th>计划 / 实际</th><th>偏差</th><th>完成程度</th><th>状态</th><th></th></tr></thead><tbody>${rows.map(r=>{const d=deviation(r,r.execution);return `<tr><td>${escapeHtml(r.taskDate)}</td><td><strong>${escapeHtml(r.taskName)}</strong><br><span class="muted">${escapeHtml(r.subject)} · ${escapeHtml(r.taskType)}</span></td><td>${fmt(r.plannedDuration)} / ${r.execution?fmt(r.execution.actualDuration):'—'} 分钟</td><td>${r.execution?`${d.minutes>=0?'+':''}${d.minutes} 分钟 (${d.rate>=0?'+':''}${d.rate.toFixed(1)}%)`:'—'}</td><td>${r.execution?escapeHtml(r.execution.completionLevel):'未记录'}</td><td>${statusPill(r.status)}</td><td><button class="action-link" data-log-task="${r.id}">${r.execution?'修改':'记录'}</button></td></tr>`}).join('')}</tbody></table></div>`:emptyState('还没有计划任务','先去学习计划页面创建一个任务。')}</div>`; bindCommon();
}
function groupStats(key){
  const groups={}; records().forEach(r=>{(groups[r[key]] ||= []).push(r);});
  return Object.entries(groups).map(([name,items])=>{const valid=items.filter(r=>r.execution);const rates=valid.map(r=>deviation(r,r.execution).rate);return {name,count:items.length,completed:items.filter(r=>r.execution?.completed).length,avgPlanned:avg(items.map(r=>+r.plannedDuration)),avgActual:avg(valid.map(r=>+r.execution.actualDuration)),avgMinutes:avg(valid.map(r=>deviation(r,r.execution).minutes)),avgRate:avg(rates),completionRate:items.length?items.filter(r=>r.execution?.completed).length/items.length*100:0};}).sort((a,b)=>b.count-a.count);
}
function periodFor(time){if(!time)return '未记录';const h=+time.slice(0,2);return h<9?PERIODS[0]:h<12?PERIODS[1]:h<15?PERIODS[2]:h<18?PERIODS[3]:h<21?PERIODS[4]:PERIODS[5];}
function periodStats(){const groups={};records().forEach(r=>{const k=periodFor(r.execution?.actualStart||r.plannedStartTime);(groups[k] ||= []).push(r);});return PERIODS.filter(p=>groups[p]).map(name=>{const items=groups[name],valid=items.filter(r=>r.execution);return {name,count:items.length,completionRate:items.filter(r=>r.execution?.completed).length/items.length*100,avgRate:avg(valid.map(r=>deviation(r,r.execution).rate)),completeRate:items.filter(r=>r.execution?.completionLevel==='完全完成').length/items.length*100};});}
function trend(days){const out=[];for(let i=days-1;i>=0;i--){const d=new Date();d.setDate(d.getDate()-i);const date=d.toISOString().slice(0,10),rows=records().filter(r=>r.taskDate===date),valid=rows.filter(r=>r.execution);out.push({date,planned:rows.reduce((s,r)=>s+ +r.plannedDuration,0),actual:valid.reduce((s,r)=>s+ +r.execution.actualDuration,0),completionRate:rows.length?rows.filter(r=>r.execution?.completed).length/rows.length*100:0,avgRate:avg(valid.map(r=>deviation(r,r.execution).rate))});}return out;}
function renderAnalysis(){
  const tabs=[['subject','科目分析'],['type','任务类型分析'],['period','时间段分析'],['week','最近 7 天趋势'],['month','最近 30 天偏差趋势']];
  let rows=[],headers=[],visual='';
  if(analysisMode==='subject'){rows=groupStats('subject');headers=['科目','任务数','平均计划','平均实际','平均偏差','偏差率','完成率'];visual=barVisual('各科平均偏差率',rows.map(r=>({label:r.name,value:r.avgRate,suffix:'%'})));}
  if(analysisMode==='type'){rows=groupStats('taskType');headers=['任务类型','任务数','平均计划','平均实际','偏差率','完成率'];visual=barVisual('各任务类型平均偏差率',rows.map(r=>({label:r.name,value:r.avgRate,suffix:'%'})));}
  if(analysisMode==='period'){rows=periodStats();headers=['时间段','任务数','完成率','平均偏差率','完全完成比例'];visual=barVisual('不同时间段完成率',rows.map(r=>({label:r.name,value:r.completionRate,suffix:'%'})));}
  if(analysisMode==='week'){rows=trend(7);headers=['日期','计划分钟','实际分钟','完成率','平均偏差率'];visual=lineVisual('最近 7 天计划与实际学习时间',rows,[['planned','计划'],['actual','实际']]);}
  if(analysisMode==='month'){rows=trend(30);headers=['日期','计划分钟','实际分钟','完成率','平均偏差率'];visual=lineVisual('最近 30 天平均偏差率变化',rows,[['avgRate','偏差率']]);}
  const valueRows=rows.map(r=>{if(analysisMode==='subject')return [r.name,r.count,`${r.avgPlanned.toFixed(0)} min`,`${r.avgActual.toFixed(0)} min`,`${r.avgMinutes>=0?'+':''}${r.avgMinutes.toFixed(0)} min`,`${r.avgRate>=0?'+':''}${r.avgRate.toFixed(1)}%`,pct(r.completionRate)];if(analysisMode==='type')return [r.name,r.count,`${r.avgPlanned.toFixed(0)} min`,`${r.avgActual.toFixed(0)} min`,`${r.avgRate>=0?'+':''}${r.avgRate.toFixed(1)}%`,pct(r.completionRate)];if(analysisMode==='period')return [r.name,r.count,pct(r.completionRate),`${r.avgRate>=0?'+':''}${r.avgRate.toFixed(1)}%`,pct(r.completeRate)];return [r.date,r.planned,r.actual,pct(r.completionRate),`${r.avgRate>=0?'+':''}${r.avgRate.toFixed(1)}%`];});
  document.querySelector('#page-analysis').innerHTML=`<div class="page-intro"><div><h3>数据分析</h3><p>只统计当前账号的真实计划和执行记录，负偏差需要结合完成程度理解。</p></div></div><div class="analysis-tabs">${tabs.map(([k,l])=>`<button class="analysis-tab ${k===analysisMode?'active':''}" data-analysis="${k}">${l}</button>`).join('')}</div><div class="panel" style="margin-bottom:18px">${visual}</div><div class="panel"><div class="table-wrap"><table class="data-table"><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${valueRows.length?valueRows.map(row=>`<tr>${row.map(v=>`<td>${escapeHtml(v)}</td>`).join('')}</tr>`).join(''):`<tr><td colspan="${headers.length}">${emptyState('还没有分析数据','先完成几条学习记录，趋势会逐渐出现。')}</td></tr>`}</tbody></table></div></div>`;
  document.querySelectorAll('[data-analysis]').forEach(el=>el.onclick=()=>{analysisMode=el.dataset.analysis;renderAnalysis();});
}
function barVisual(title,items){
  if(!items.length)return emptyState('暂无足够数据','完成执行记录后，这里会出现可比较的分布。');
  const values=items.map(x=>Number(x.value)||0),min=Math.min(0,...values),max=Math.max(0,...values),span=Math.max(max-min,1),width=760,height=Math.max(220,items.length*42+52),left=142,right=72,top=32,bottom=18,plotW=width-left-right,rowH=(height-top-bottom)/items.length,xFor=v=>left+(v-min)/span*plotW,zero=xFor(0);
  const ticks=Array.from({length:5},(_,i)=>min+(span*i/4));
  const grid=ticks.map(v=>`<line x1="${xFor(v).toFixed(1)}" y1="${top-8}" x2="${xFor(v).toFixed(1)}" y2="${height-bottom}" class="chart-grid-line"/><text x="${xFor(v).toFixed(1)}" y="18" text-anchor="middle" class="chart-axis-label">${v>=0?'+':''}${v.toFixed(0)}%</text>`).join('');
  const bars=items.map((item,i)=>{const value=Number(item.value)||0,y=top+i*rowH+rowH*.2,h=Math.min(22,rowH*.55),x=value>=0?zero:xFor(value),w=Math.max(Math.abs(xFor(value)-zero),2),color=value>=0?'#326b62':'#c9854c';return `<text x="${left-12}" y="${(y+h/2+4).toFixed(1)}" text-anchor="end" class="chart-label">${escapeHtml(item.label)}</text><rect x="${x.toFixed(1)}" y="${y.toFixed(1)}" width="${w.toFixed(1)}" height="${h.toFixed(1)}" rx="4" fill="${color}"/><text x="${(value>=0?x+w+8:x-8).toFixed(1)}" y="${(y+h/2+4).toFixed(1)}" text-anchor="${value>=0?'start':'end'}" class="chart-value">${value>=0?'+':''}${value.toFixed(1)}${item.suffix||''}</text>`;}).join('');
  return `<div class="panel-head"><h4>${escapeHtml(title)}</h4><span>历史记录</span></div><div class="chart-wrap"><svg class="chart-svg" viewBox="0 0 ${width} ${height}" role="img" aria-label="${escapeHtml(title)}">${grid}<line x1="${zero.toFixed(1)}" y1="${top-8}" x2="${zero.toFixed(1)}" y2="${height-bottom}" class="chart-zero-line"/>${bars}</svg></div>`;
}
function lineVisual(title,rows,series){
  if(!rows.some(r=>series.some(([key])=>Number(r[key])!==0)))return emptyState('暂无趋势数据','有执行记录的日期会在这里形成趋势。');
  const values=series.flatMap(([key])=>rows.map(r=>Number(r[key])||0)),rawMin=Math.min(...values),rawMax=Math.max(...values),pad=Math.max((rawMax-rawMin)*.12,rawMax===0?1:Math.abs(rawMax)*.08),min=rawMin-pad,max=rawMax+pad,width=760,height=290,left=48,right=20,top=28,bottom=42,plotW=width-left-right,plotH=height-top-bottom,xFor=i=>left+(rows.length===1?plotW/2:i/(rows.length-1)*plotW),yFor=v=>top+(max-v)/(max-min)*plotH;
  const yTicks=Array.from({length:5},(_,i)=>min+(max-min)*i/4),grid=yTicks.map(v=>`<line x1="${left}" y1="${yFor(v).toFixed(1)}" x2="${width-right}" y2="${yFor(v).toFixed(1)}" class="chart-grid-line"/><text x="${left-10}" y="${(yFor(v)+4).toFixed(1)}" text-anchor="end" class="chart-axis-label">${v.toFixed(0)}</text>`).join('');
  const labels=rows.map((r,i)=>{if(rows.length>10&&i!==0&&i!==rows.length-1&&i%Math.ceil(rows.length/6)!==0)return '';return `<text x="${xFor(i).toFixed(1)}" y="${height-12}" text-anchor="middle" class="chart-axis-label">${escapeHtml(r.date.slice(5))}</text>`;}).join('');
  const palette=['#326b62','#c9854c','#5d7f74'];
  const lines=series.map(([key,label],seriesIndex)=>{const points=rows.map((r,i)=>`${xFor(i).toFixed(1)},${yFor(Number(r[key])||0).toFixed(1)}`).join(' '),dots=rows.map((r,i)=>`<circle cx="${xFor(i).toFixed(1)}" cy="${yFor(Number(r[key])||0).toFixed(1)}" r="3.5" fill="${palette[seriesIndex%palette.length]}"/>`).join('');return `<polyline points="${points}" fill="none" stroke="${palette[seriesIndex%palette.length]}" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"/>${dots}`;}).join('');
  const legend=series.map(([key,label],i)=>`<span class="chart-legend-item"><i style="background:${palette[i%palette.length]}"></i>${escapeHtml(label)}</span>`).join('');
  return `<div class="panel-head"><h4>${escapeHtml(title)}</h4><span class="chart-legend">${legend}</span></div><div class="chart-wrap"><svg class="chart-svg" viewBox="0 0 ${width} ${height}" role="img" aria-label="${escapeHtml(title)}">${grid}${lines}${labels}</svg></div>`;
}
function getRecommendations(){
  const rec=[];groupStats('subject').forEach(r=>{if(r.count>=5&&r.avgRate>20)rec.push(`近期${r.name}任务实际用时平均高于计划约 ${r.avgRate.toFixed(0)}%，下次可适当增加计划时长。`);});groupStats('taskType').forEach(r=>{if(r.count>=5&&r.avgRate>40)rec.push(`你在“${r.name}”类任务上经常低估所需时间，建议增加时间余量。`);if(r.count>=5&&r.avgRate<-20&&r.completionRate>=80)rec.push(`“${r.name}”通常比计划时间提前完成，且完成程度较高，后续可适当缩短安排。`);});const ps=periodStats(),base=avg(ps.map(r=>r.completionRate));ps.forEach(r=>{if(r.count>=8&&r.completionRate<base-15)rec.push(`你的${r.name}任务执行完成率相对较低，重要任务可以尝试提前安排。`);});const t=trend(14),a=t.slice(-7).filter(x=>x.avgRate).map(x=>Math.abs(x.avgRate)),b=t.slice(0,7).filter(x=>x.avgRate).map(x=>Math.abs(x.avgRate));if(a.length&&b.length&&avg(a)<avg(b)*.8)rec.push('最近一周计划时间与实际执行更加接近，你的学习时间估计正在逐步改善。');return rec.length?rec:['继续记录学习任务后，系统将逐步生成个性化建议。'];
}
function renderRecommendations(){const rec=getRecommendations();const stats=groupStats('subject').sort((a,b)=>b.avgRate-a.avgRate);document.querySelector('#page-recommendations').innerHTML=`<div class="page-intro"><div><h3>学习建议</h3><p>建议只来自你的历史数据，记录越完整，结论越具体。</p></div></div><div class="recommendation-grid"><div class="panel"><div class="panel-head"><h4>给你的下一步</h4><span>${rec.length} 条建议</span></div>${rec.map((r,i)=>`<div class="rec-card"><div class="rec-tag">建议 ${String(i+1).padStart(2,'0')}</div><p>${escapeHtml(r)}</p></div>`).join('')}</div><div class="panel"><div class="panel-head"><h4>最需要观察的科目</h4><span>按平均偏差率</span></div>${stats.length?barVisual('',stats.slice(0,5).map(r=>({label:r.name,value:r.avgRate,suffix:'%'}))):emptyState('暂无科目数据','完成任务后再回来看看。')}</div></div>`;}
function renderProfile(){const rows=records(),minutes=rows.reduce((s,r)=>s+(r.execution?.actualDuration||0),0);document.querySelector('#page-profile').innerHTML=`<div class="page-intro"><div><h3>我的</h3><p>管理账号信息，导出或清理自己的学习数据。</p></div></div><div class="profile-grid"><div class="profile-card"><h4>学习概览</h4><div class="profile-summary"><div><strong>${rows.length}</strong><span>累计任务</span></div><div><strong>${fmt(minutes)}</strong><span>实际学习分钟</span></div><div><strong>${escapeHtml(currentUser.createdAt.slice(0,10))}</strong><span>注册日期</span></div><div><strong>${currentUser.username}</strong><span>用户名</span></div></div><div class="tip-box" style="margin-top:16px">数据只保存在这台设备的浏览器中，不会上传到网络。</div></div><div class="profile-card"><h4>修改昵称</h4><form id="nicknameForm"><label>昵称<input id="profileNickname" required value="${escapeHtml(currentUser.nickname)}"></label><button class="primary" type="submit">保存昵称</button></form><h4 style="margin-top:28px">修改密码</h4><form id="passwordForm"><label>当前密码<input id="oldPassword" type="password" required></label><label>新密码<input id="newPassword" type="password" minlength="6" required></label><button class="ghost" type="submit">修改密码</button></form></div><div class="profile-card"><h4>数据工具</h4><p class="muted">导出一份 CSV 备份，或清空当前账号的学习记录。</p><button class="ghost" id="exportData">导出 CSV</button></div><div class="profile-card danger-zone"><h4>清空学习记录</h4><p class="muted">会删除当前账号的任务和执行记录，不会删除账号。</p><button class="ghost" id="clearData">清空我的记录</button></div></div>`;document.querySelector('#nicknameForm').onsubmit=e=>{e.preventDefault();const v=document.querySelector('#profileNickname').value.trim();if(v){currentUser.nickname=v;db.users.find(u=>u.id===currentUser.id).nickname=v;saveDb();updateUserMeta();showToast('昵称已更新');}};document.querySelector('#passwordForm').onsubmit=async e=>{e.preventDefault();const old=document.querySelector('#oldPassword').value,nw=document.querySelector('#newPassword').value,u=db.users.find(x=>x.id===currentUser.id);if(nw.length<6)return showToast('新密码至少 6 个字符');if(!(await verifyPassword(old,u.passwordHash,u.salt)))return showToast('当前密码不正确');u.salt=randomSalt();u.passwordHash=await hashPassword(nw,u.salt);saveDb();e.target.reset();showToast('密码已修改');};document.querySelector('#exportData').onclick=exportData;document.querySelector('#clearData').onclick=()=>{if(confirm('确定清空当前账号的全部学习记录吗？此操作不可恢复。')){db.tasks=db.tasks.filter(t=>t.userId!==currentUser.id);db.executions=db.executions.filter(e=>e.userId!==currentUser.id);saveDb();renderProfile();showToast('学习记录已清空');}};}
function updateUserMeta(){document.querySelector('#topNickname').textContent=currentUser.nickname;document.querySelector('#topUsername').textContent=`@${currentUser.username}`;document.querySelector('#avatar').textContent=(currentUser.nickname||'学').slice(0,1);}
function fillOptions(){document.querySelector('#taskSubject').innerHTML=SUBJECTS.map(s=>`<option>${s}</option>`).join('');document.querySelector('#taskType').innerHTML=TASK_TYPES.map(s=>`<option>${s}</option>`).join('');}
function openTask(taskId=null){const form=document.querySelector('#taskForm');form.reset();document.querySelector('#taskDate').value=today();document.querySelector('#taskStart').value='19:00';document.querySelector('#taskDuration').value=45;document.querySelector('#taskId').value=taskId||'';document.querySelector('#taskDialogTitle').textContent=taskId?'编辑学习任务':'新建学习任务';const t=taskId&&db.tasks.find(x=>x.id===taskId);if(t){for(const [id,value] of [['taskDate',t.taskDate],['taskSubject',t.subject],['taskName',t.taskName],['taskType',t.taskType],['taskStart',t.plannedStartTime],['taskDuration',t.plannedDuration],['taskDifficulty',t.difficulty],['taskPriority',t.priority],['taskStatus',t.status],['taskNotes',t.notes]])document.querySelector(`#${id}`).value=value||'';}updateSuggestion();document.querySelector('#taskDialog').showModal();}
function updateSuggestion(){const s=document.querySelector('#durationSuggestion'),t=records().filter(r=>r.subject===document.querySelector('#taskSubject').value&&r.taskType===document.querySelector('#taskType').value&&r.difficulty===document.querySelector('#taskDifficulty').value&&r.execution?.actualDuration);if(t.length<3){s.classList.add('hidden');return;}const a=avg(t.slice(-10).map(r=>+r.execution.actualDuration));s.textContent=`历史类似任务平均实际用时：${a.toFixed(0)} 分钟；建议计划时长：${Math.max(1,a-3).toFixed(0)}–${(a+3).toFixed(0)} 分钟`;s.classList.remove('hidden');}
function saveTask(){const idv=document.querySelector('#taskId').value||id(),data={id:idv,userId:currentUser.id,taskDate:document.querySelector('#taskDate').value,subject:document.querySelector('#taskSubject').value,taskName:document.querySelector('#taskName').value.trim(),taskType:document.querySelector('#taskType').value,plannedStartTime:document.querySelector('#taskStart').value,plannedDuration:+document.querySelector('#taskDuration').value,difficulty:document.querySelector('#taskDifficulty').value,priority:document.querySelector('#taskPriority').value,status:document.querySelector('#taskStatus').value,notes:document.querySelector('#taskNotes').value.trim(),createdAt:new Date().toISOString()};if(!data.taskDate||!data.taskName||!data.plannedDuration)return showToast('请填写日期、任务名称和计划时长');const i=db.tasks.findIndex(t=>t.id===idv);if(i>=0)db.tasks[i]={...db.tasks[i],...data};else db.tasks.push(data);saveDb();document.querySelector('#taskDialog').close();showToast(i>=0?'任务已更新':'任务已创建');renderPage(activePage);}
function openExecution(taskId=null){const select=document.querySelector('#executionTask');const rows=records();select.innerHTML=rows.map(r=>`<option value="${r.id}">${escapeHtml(r.taskDate)} · ${escapeHtml(r.subject)} · ${escapeHtml(r.taskName)}</option>`).join('');if(taskId)select.value=taskId;const ex=db.executions.find(e=>e.taskId===select.value);document.querySelector('#actualStart').value=ex?.actualStart||'';document.querySelector('#actualEnd').value=ex?.actualEnd||'';document.querySelector('#actualDuration').value=ex?.actualDuration??45;document.querySelector('#completionLevel').value=ex?.completionLevel||'完全完成';document.querySelector('#completed').value=ex?.completed?'1':'0';document.querySelector('#interrupted').value=ex?.interrupted?'1':'0';document.querySelector('#selfEvaluation').value=ex?.selfEvaluation||3;document.querySelector('#executionNotes').value=ex?.notes||'';document.querySelector('#executionDialog').showModal();}
function saveExecution(){const taskId=document.querySelector('#executionTask').value;if(!taskId)return showToast('请先创建学习计划');let duration=+document.querySelector('#actualDuration').value,start=document.querySelector('#actualStart').value,end=document.querySelector('#actualEnd').value;if(start&&end){const a=new Date(`1970-01-01T${start}`),b=new Date(`1970-01-01T${end}`);duration=Math.max(0,Math.round((b-a)/60000));document.querySelector('#actualDuration').value=duration;}const ex={id:id(),userId:currentUser.id,taskId,actualStart:start,actualEnd:end,actualDuration:duration,completionLevel:document.querySelector('#completionLevel').value,completed:document.querySelector('#completed').value==='1'||document.querySelector('#completionLevel').value==='完全完成',interrupted:document.querySelector('#interrupted').value==='1',selfEvaluation:+document.querySelector('#selfEvaluation').value,notes:document.querySelector('#executionNotes').value.trim(),createdAt:new Date().toISOString()};const i=db.executions.findIndex(e=>e.taskId===taskId&&e.userId===currentUser.id);if(i>=0)db.executions[i]={...db.executions[i],...ex};else db.executions.push(ex);const task=db.tasks.find(t=>t.id===taskId);task.status=ex.completed?'已完成':duration?'进行中':'待完成';saveDb();document.querySelector('#executionDialog').close();showToast('执行记录已保存');renderPage(activePage);}
function deleteTask(taskId){if(confirm('确定删除这个任务及其执行记录吗？')){db.tasks=db.tasks.filter(t=>t.id!==taskId);db.executions=db.executions.filter(e=>e.taskId!==taskId);saveDb();renderPage(activePage);showToast('任务已删除');}}
function exportData(){const rows=records(),header=['日期','科目','任务','类型','计划开始','计划分钟','状态','实际分钟','完成程度','偏差分钟','偏差率'];const lines=[header,...rows.map(r=>{const d=deviation(r,r.execution);return [r.taskDate,r.subject,r.taskName,r.taskType,r.plannedStartTime,r.plannedDuration,r.status,r.execution?.actualDuration??'',r.execution?.completionLevel??'',r.execution?d.minutes:'',r.execution?d.rate.toFixed(1)+'%':''];})].map(row=>row.map(v=>`"${String(v).replaceAll('"','""')}"`).join(','));const blob=new Blob(['\ufeff'+lines.join('\n')],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`study_plan_${today()}.csv`;a.click();URL.revokeObjectURL(a.href);showToast('CSV 已导出');}
async function hashPassword(password,salt){const enc=new TextEncoder();const key=await crypto.subtle.importKey('raw',enc.encode(password),'PBKDF2',false,['deriveBits']);const bits=await crypto.subtle.deriveBits({name:'PBKDF2',salt:enc.encode(salt),iterations:120000,hash:'SHA-256'},key,256);return [...new Uint8Array(bits)].map(b=>b.toString(16).padStart(2,'0')).join('');}
async function verifyPassword(password,hash,salt){return await hashPassword(password,salt)===hash;}
function randomSalt(){const a=new Uint8Array(16);crypto.getRandomValues(a);return [...a].map(b=>b.toString(16).padStart(2,'0')).join('');}
function openApp(user){currentUser=user;document.querySelector('#authView').classList.add('hidden');document.querySelector('#appView').classList.remove('hidden');updateUserMeta();setPage('dashboard');}
function showAuth(mode){document.querySelectorAll('.auth-tab').forEach(t=>t.classList.toggle('active',t.dataset.auth===mode));document.querySelector('#loginForm').classList.toggle('hidden',mode!=='login');document.querySelector('#registerForm').classList.toggle('hidden',mode!=='register');}
function bindCommon(){document.querySelectorAll('[data-open-task]').forEach(el=>el.onclick=()=>openTask());document.querySelectorAll('[data-open-execution]').forEach(el=>el.onclick=()=>openExecution());document.querySelectorAll('[data-edit-task]').forEach(el=>el.onclick=()=>openTask(el.dataset.editTask));document.querySelectorAll('[data-delete-task]').forEach(el=>el.onclick=()=>deleteTask(el.dataset.deleteTask));document.querySelectorAll('[data-log-task]').forEach(el=>el.onclick=()=>openExecution(el.dataset.logTask));}
function init(){
  fillOptions();
  document.querySelectorAll('[data-auth]').forEach(el=>el.onclick=()=>showAuth(el.dataset.auth));
  document.querySelectorAll('[data-toggle-password]').forEach(el=>el.onclick=()=>{const i=document.querySelector('#'+el.dataset.togglePassword);i.type=i.type==='password'?'text':'password';el.textContent=i.type==='password'?'显示':'隐藏';});
  document.querySelectorAll('.nav-item').forEach(el=>el.onclick=()=>setPage(el.dataset.page));
  document.querySelector('#quickAdd').onclick=()=>openTask();
  document.querySelector('#logoutBtn').onclick=()=>{currentUser=null;document.querySelector('#appView').classList.add('hidden');document.querySelector('#authView').classList.remove('hidden');showAuth('login');showToast('已退出登录');};
  document.querySelector('#loginForm').onsubmit=async e=>{e.preventDefault();const username=document.querySelector('#loginUsername').value.trim(),password=document.querySelector('#loginPassword').value,u=db.users.find(x=>x.username===username);if(!u||!(await verifyPassword(password,u.passwordHash,u.salt)))return showToast('用户名或密码错误');if(document.querySelector('#rememberUsername').checked)localStorage.setItem('spa_last_user',username);openApp(u);};
  const remembered=localStorage.getItem('spa_last_user');if(remembered)document.querySelector('#loginUsername').value=remembered;
  document.querySelector('#registerForm').onsubmit=async e=>{e.preventDefault();const username=document.querySelector('#registerUsername').value.trim(),nickname=document.querySelector('#registerNickname').value.trim(),password=document.querySelector('#registerPassword').value,confirmPassword=document.querySelector('#registerConfirm').value;if(username.length<3)return showToast('用户名至少 3 个字符');if(!nickname)return showToast('昵称不能为空');if(password.length<6)return showToast('密码至少 6 个字符');if(password!==confirmPassword)return showToast('两次密码不一致');if(db.users.some(x=>x.username===username))return showToast('用户名已存在');const salt=randomSalt(),user={id:id(),username,nickname,salt,passwordHash:await hashPassword(password,salt),createdAt:new Date().toISOString()};db.users.push(user);saveDb();showAuth('login');document.querySelector('#loginUsername').value=username;document.querySelector('#loginPassword').value='';showToast('注册成功，请登录');};
  document.querySelector('#taskForm').onsubmit=e=>{e.preventDefault();saveTask();};document.querySelector('#executionForm').onsubmit=e=>{e.preventDefault();saveExecution();};document.querySelectorAll('#taskSubject,#taskType,#taskDifficulty').forEach(el=>el.addEventListener('change',updateSuggestion));document.querySelector('#actualStart').addEventListener('change',()=>{if(document.querySelector('#actualStart').value&&document.querySelector('#actualEnd').value)document.querySelector('#actualDuration').value=Math.max(0,Math.round((new Date(`1970-01-01T${document.querySelector('#actualEnd').value}`)-new Date(`1970-01-01T${document.querySelector('#actualStart').value}`))/60000));});document.querySelector('#actualEnd').addEventListener('change',()=>document.querySelector('#actualStart').dispatchEvent(new Event('change')));
  bindCommon();
}
init();
